#!/bin/sh

killall looping

echo chatserver
./chatserver >/dev/null &
sleep 1
./server -a 1 -d
sleep 1
#./server -a 2 -d
#sleep 1
./server -a 3 -d
sleep 1
#./server -a 13 -d
#sleep 1
#./server -a 14 -d
#sleep 1
#./server -a 15 -d
#sleep 1
#./server -a 16 -d
#sleep 1
#./server -a 17 -d
#sleep 1
#./server -a 19 -d
#sleep 1
#./server -a 26 -d
#sleep 1
./looping & # a 27
sleep 1
#./server -a 28 -d
#sleep 1
#./server -a 29 -d
#sleep 1
#./server -a 30 -d
#sleep 1
#./server -a 35 -d
#sleep 1
#./server -a 36 -d
#sleep 1
#./server -a 37 -d
#sleep 1
echo DONE

